baseURL = 'https://are-we-gfx1100-yet.github.io/'
languageCode = 'en-us'
title = 'Are we gfx1100 yet?'
theme = 'hugo-theme-stack'

[params]
dataFormat.published = 'Jan 01, 2000'
article.license.enabled = true
footer.customText = 'If my work has been helpful to you, please send me a star on GitHub!'

[params.widgets]

[[params.widgets.homepage]]
type = 'archives'
params.limit = 3

[[params.widgets.homepage]]
type = 'tag-cloud'
params.limit = 10

[[params.widgets.page]]
type = 'toc'

[main]

[[menu.social]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/evshiron'
params.icon = 'brand-github'

[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
params.icon = 'home'
weight = -100

[[menu.main]]
identifier = 'discussions'
name = 'Discussions'
url = 'https://github.com/evshiron/are-we-gfx1100-yet/discussions'
params.icon = 'messages'
weight = 80

[[menu.main]]
identifier = 'rocm_lab'
name = 'ROCm LAB'
url = 'https://github.com/evshiron/rocm_lab'
params.icon = 'brand-github'
weight = 90

[[menu.main]]
identifier = 'source'
name = 'Source'
url = 'https://github.com/evshiron/are-we-gfx1100-yet'
params.icon = 'brand-github'
weight = 100
