baseURL = 'https://evshiron.github.io/are-we-gfx1100-yet/'
languageCode = 'en-us'
title = 'Are we gfx1100 yet?'
theme = 'hugo-theme-stack'

[params]
dataFormat.published = 'Jan 01, 2000'
article.license.enabled = true

[main]

[[menu.social]]
identifier = 'github'
name = 'GitHub'
url = 'https://github.com/evshiron'
params.icon = 'brand-github'

[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/'
params.icon = 'home'
weight = -100

[[menu.main]]
identifier = 'discussions'
name = 'Discussions'
url = 'https://github.com/evshiron/are-we-gfx1100-yet/discussions'
params.icon = 'messages'
weight = 90

[[menu.main]]
identifier = 'source'
name = 'Source'
url = 'https://github.com/evshiron/are-we-gfx1100-yet'
params.icon = 'brand-github'
weight = 100
